### ISSUE TITLE
st2workroom_upgrade_test improvements

### ISSUE THREAD

**Issue by manasdk** [StackStorm/st2cd#127]
Pick up todo from https://github.com/StackStorm/st2cd/pull/124
- [ ] Add rules and hook it up to our release pipeline
- [ ] Retry on failure policy to mitigate false negatives due to intermediate network issues
- [ ] Refactor the code and split it into multiple smaller actions / workflows which can be-reused in other workflows (future improvement)
- [ ] Based it on top of the enterprise tests since those should be a super-set of non-enterprise tests (future improvement)
- [ ] Also run those tests on  RHEL / EL (future improvements)

**Comment by LindsayHill** [comment]
workroom stuff has gone a while back
