### ISSUE TITLE
There are two docs workflows - One script and One workflow. Deprecate one!

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2cd#198]
Release uses https://github.com/StackStorm/st2cd/blob/master/actions/st2_make_docs.sh

Regular commits use https://github.com/StackStorm/st2cd/blob/master/actions/workflows/st2_docs.yaml

Figure out why a new one was written and if makes sense deprecate one or another.

**Comment by LindsayHill** [comment]
docs workflows completely changed recently, CircleCI does it all now
