### ISSUE TITLE
Update e2e test rules as part of post-release tasks

### ISSUE THREAD

**Issue by Mierdin** [StackStorm/st2cd#263]
All of the rules that perform e2e testing daily are still using an old version of stackstorm:
https://github.com/StackStorm/st2cd/blob/master/rules/st2_pkg_test_stable_u14.yaml#L24.
PRs like https://github.com/StackStorm/st2cd/pull/237 updated these manually, but it's not part of the release wiki, and so it wasn't done for the last few releases.

We need to write an action or workflow to update these automatically as part of the post-release tasks. Someone should probably create workflows to go through all of the rules in st2cd (and st2ci if applicable) that have versions listed in args and update them.

Ideally, this would just get added as a step to `st2_prep_release_rules` as that action already does similar things, and it's already run at the end of both full and patch releases.

**Comment by Mierdin** [comment]
As it turns out, this was already implemented by @bigmstone in https://github.com/StackStorm/st2cd/pull/239. However, it looks like the release immediately following the implementation of that PR either didn't work, or perhaps used the wrong "previous" version, since the script requires a correct previous version in order for the sed replace to work. And I know when I ran 2.2.0, I specified 2.1.1, which would not have matched the sed (as these rules still specify 2.1.0).

So, that leaves a few things left to do:

- [x] https://github.com/StackStorm/st2cd/pull/264 needs to be merged, so that the current rules can reflect the current version (remember to `git pull` and `st2ctl reload` once done).
- [x] Since 2.2.1 release is imminent, I'll debug `st2_prep_release_rules` and ensure that the rules get automatically updated from 2.2.0 to 2.2.1
- [x]  We need to add a step in the wiki to "clean" local `st2cd` and `st2ci` repos before release starts by checking for uncommitted changes, and doing a fresh pull and `st2ctl reload --register-all`. This will be necessary until #256 is implemented

**Comment by Mierdin** [comment]
@bigmstone can you comment on the 3rd TODO from above? Will your build node efforts automatically pull and load the latest `st2ci` and `st2cd` repos?

**Comment by bigmstone** [comment]
@Mierdin the build node will always pull in latest `master` for both repos, yes. That said there's no rule set up to do this on a continual basis. That said the fact that the build node gets destroyed every push to st2 master should remove the issue of people making changes on the server. :)

**Comment by Mierdin** [comment]
That's a bit what I was getting at - basically as long as both repos get a fresh clone every time the build node is built, answers my question. It means I don't have to spend time writing workflows to do this

**Comment by Mierdin** [comment]
Everything has been taking care of in other PRs/issues, so closing this
