### ISSUE TITLE
Automated updates for API docs

### ISSUE THREAD

**Issue by Mierdin** [StackStorm/st2cd#316]
On adding the Inquiries API endpoints in 2.5, I was (apparently mistakenly) under the impression that this was automatically generated based on the OpenAPI spec. However, after 2.5, https://api.stackstorm.com/ still does not contain the Inquiries set of endpoints.

We should first update the API docs to include these through whatever manual process (should be documented) is required today. Then we should consider adding steps to the release workflows that perform this update for every time we release StackStorm.

**Comment by Mierdin** [comment]
@enykeev ran this manually to fix for now - To build a new version of api docs, one need to rerun the latest master build in https://circleci.com/gh/StackStorm/st2apidocs

So we should update release process to include this step

**Comment by LindsayHill** [comment]
Resolved a while back with https://github.com/StackStorm/st2cd/pull/344
