### ISSUE TITLE
st2cd.bwc_prep_patch action needs to bump / set st2_version in package.json in bwc-ui

### ISSUE THREAD

**Issue by Kami** [StackStorm/st2cd#327]
I notice that we don't do that while working on 2.7.1 release.

I checked previous patch releases and package.json didn't exist yet when we did last patch release (2.5.1).

We need to update this workflow to set "st2_version" attribute in package.json to match `version` parameter passed to the action - https://github.com/StackStorm/bwc-ui/commit/4e9a3afac140e9d899efa356d08c9a076a94e087.

This attribute is also used to set version for bwc-ui packages.

**Comment by arm4b** [comment]
@Kami See https://github.com/StackStorm/discussions/issues/284

Looks like @lakshmi-kannan noticed the same and worked on fixes after the previous release, PRs:
- https://github.com/StackStorm/st2cd/pull/323
- https://github.com/StackStorm/st2cd/pull/322

Could be good to start looking from there. Might be some bug in code not handling the patch release or similar.

**Comment by Kami** [comment]
@armab Thanks - I will look into it tomorrow. The workflow / action is idempotent anyway so it shouldn't hurt if I run it multiple time when the version is already set.

**Comment by blag** [comment]
Is this still relevant? I think bwc-ui is now dead, so we should mark this as done in the [EWC Open Source Migration project](https://github.com/orgs/StackStorm/projects/14#card-42916227).

**Comment by arm4b** [comment]
+1 definitely could be closed as `bwc-ui` repo is gone.
Fewer repos, less moving pieces, and dependency problems :)
